### ISSUE TITLE
Manually set up some HTML Apps using the OVE front end

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/gridlington-vis#11]

**Comment by dandavies99** [comment]
This seems to work with HTML apps pointing to the correct port and address on the VM. 

![Image](https://user-images.githubusercontent.com/5871253/215069514-9e711781-2360-4f0a-b7c9-48f60762c84f.png)

**Comment by dandavies99** [comment]
Suggest we consider this achieved unless there's anything else specific you want to test @AdrianDAlessandro?

**Comment by AdrianDAlessandro** [comment]
I cannot see any sections currently connected... Are they still running and set up when you look?

**Comment by dandavies99** [comment]
No there are none running now, which you can check on the OVE landing page - http://liionsden.rcs.ic.ac.uk:8080/. The app was restarted after merging in changes from #18.

Feel free to start apps yourself though. Just point them to e.g. http://liionsden.rcs.ic.ac.uk:8050/plot1.

**Comment by AdrianDAlessandro** [comment]
Ok, I say we keep this issue open until we have tested them in the room. The purpose of manually launching them is so they're ready for testing.

**Comment by AdrianDAlessandro** [comment]
They're set up for now, let's see if they persist until Tuesday

**Comment by dandavies99** [comment]
These have now been tested in the room.
