### ISSUE TITLE
Questions for running in demo room

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/gridlington-vis#13]
List of questions / things to check when running in the Demo room: 

- [x] What dimensions should each of the spaces be? 
- [x] Generate some schematic / diagram to map the OVE spaces to the physical monitors and computers in the room.
- [x] Is the current http configuration suitable?
- [x] Can we initiate sections using the API?
- [x] Can we switch / delete sections using the API?

Aha! Link: https://imperial-college-ict.aha.io/requirements/RSE-139-11

**Comment by dandavies99** [comment]
All of these questions have been answered.

- What dimensions should each of the spaces be? ➡ #19 
- Generate some schematic / diagram to map the OVE spaces to the physical monitors and computers in the room. ➡  on [Whimsical board](https://whimsical.com/idles-LP5cXQpyXNxtqA8fr6BKA9).
- Is the current http configuration suitable? ➡ There were no problems in the demo room.
- Can we initiate sections using the API? ➡  Yes, currently demonstrated on `api_test` branch, to be merged in.
- Can we switch / delete sections using the API?  ➡  Yes, currently demonstrated on `api_test` branch, to be merged in.

We can either close the issue now or when the api changes have been merged in.

**Comment by AdrianDAlessandro** [comment]
Happy to close this. Questions were answers, details being implemented in `api_test` branch are related to #6 #7 and #9
