### ISSUE TITLE
https configuration

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/gridlington-vis#17]
**Problem:**

The current system running on the VM does not use TLS/SSL so can't handle https requests. Hitherto attempts to configure the nginx `default.conf` file to use ssl certificates have resulted in partial success: The OVE landing page is accessible at https://...:8080 but other sub-pages e.g. the application launcher are not. When a GET request is made for these pages, nginx logs the following: 

```
[info]: client sent plain HTTP request to HTTPS port while reading client request headerrss, client: 172.25.0.1, server: liionsden.rcs.ic.ac.uk, request: "GET / HTTP/1.1", host: "146.179.34.13:8080"
```

and only a blank white page can be accessed. 

Additionally, the usual background `[TRACE]` logs e.g. 

```
[TRACE] 25/01/2023, 1:04:16.426 pm - audio            : Responded to sync request
```

are replaced with an `[ERROR]` e.g.:

```
[ERROR] 25/01/2023, 11:13:26.902 am - audio            : Error: Unexpected server response: 400
    at ClientRequest.req.on (/usr/src/app/node_modules/ws/lib/websocket.js:579:7)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
    at Socket.socketOnData (_http_client.js:451:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
 ```

**Proposed solution:**

It is possible to [configure https servers with nginx](http://nginx.org/en/docs/http/configuring_https_servers.html). There is also a [useful looking blog post](https://www.tecmint.com/fix-400-bad-request-in-nginx/) with an example `.conf` file that is similar to our setup. 

**Additional context:**

At the moment, to access the server running on the VM a http://... address is needed (not https://). Some browsers will automatically convert http:// to https:// if you have previously visited the site with https://. For Chrome, see [these instructions to stop the automatic redirection](https://superuser.com/a/881431).

Aha! Link: https://imperial-college-ict.aha.io/requirements/RSE-139-14

**Comment by dandavies99** [comment]
After tests in the demonstrator room, it seems that https is not required, and http requests worked fine to the VM from all the PCs and MS Hubs. Suggest we close this issue @AdrianDAlessandro. Could then reopen if it becomes a problem.

**Comment by AdrianDAlessandro** [comment]
Yes, agreed
