### ISSUE TITLE
Convert API functions to Object Oriented format

### ISSUE THREAD

**Issue by CWestICL** [ImperialCollegeLondon/gridlington-vis#22]
Convert the current `api-test.py` functions into an Object Orientated format using [Uplink](https://uplink.readthedocs.io/en/stable/).

Ensure some of the initial apps are WebRTC Apps (related to #12)

Aha! Link: https://imperial-college-ict.aha.io/requirements/RSE-139-15

**Comment by AdrianDAlessandro** [comment]
This is no longer required, the current implementation with `requests` is fit for purpose
