### ISSUE TITLE
Market view

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/gridlington-vis#34]
This is a more local view of the markets at play. Some of the data is the same as above so that it is all kept together. The more local markets are the DSR (Demand-Side Response) systems which would represent aggregators that bring together the demand flexibility of a number of users to sell it on the intra-day or balancing markets. The aggregators would be in the market giving their bids and receiving their offers and would then pass the commands down to the individual users. This is still a little vague at our end as it is a mechanism we have yet to design.
- Day Ahead market system – Line graph showing closing prices? Needs more thought
- Balancing requirements – Line graph with multiple lines showing demand to different balancing mechanisms
- Energy Deficit – Line Graph
- Intraday market bids and offers – This would be a list/table I think. Maybe coloured by acceptance of bids?
- DSR Bids and offers – As above
- DSR commands to agents – Line graph?

**Proposed Solution:**
See description in #29 

Aha! Link: https://imperial-college-ict.aha.io/requirements/RSE-140-8

**Comment by AdrianDAlessandro** [comment]
![Image](https://github.com/ImperialCollegeLondon/gridlington-vis/assets/40875798/d26a2863-fb43-4b63-a53f-918f7c286fc6)

**Comment by CWestICL** [comment]
Info needed for plotting the graphs in this view. Might be worth checking in with Phil and Yue to clarify what data exactly is being represented here.

**Comment by AdrianDAlessandro** [comment]
- Day Ahead market system – Replace with "Intra-day Market System"
  - Double y-axis graph: Power (MW) & Cost (£/MW)
  - Power: `intra_gen`, `intra_sto`, `intra_dem`
  - Cost `intra_trade`
- Balancing requirements - Rename to Balancing Market
  - Double y-axis graph: Power (MW) & Cost (£/MW)
  - Power: `bm_gen`, `bm_sto`, `bm_dem`
  - Cost `bm_cost`
- Energy Deficit – Currently `offwind_exp - offwind_real` (not happy with this - it's only a specific case)
- Intraday market bids and offers – Don't appear to be in the data
- DSR Bids and offers – Don't appear to be in the data
- DSR commands to agents
  - Exists somewhere, not sure which data source
  - Graph will be three lines:
    - Top line a line graph of Commands(?) with area filled in underneath
    - `real_dem - exp_dem + (real_ev - exp_ev)`
    - `real_ev - exp_ev`
