### ISSUE TITLE
Agent view

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/gridlington-vis#35]
Going still further down to the ground level we have the agents themselves. These are representations of the population of our fictional town. Some of the population have EVs which are represented by another agent. They have their own activities which they are doing at any given time (shown in a plot) and participate in the DSR system above where possible. We would like to show where the agents are physically in the town and what they are doing at any given time.
- Map showing agent locations – Essentially an image with dots overlaid at certain locations. Dots resize to represent number of agents
- Agent location on SLD (single line diagram schematic) – As above but a different image
- EV Location on Map
- EV Location on SLD
- Agent activity breakdown – A grid of icons representing agents. Coloured by activity
- EV charging breakdown – As above but EVs
- DSR commands to agents – Line graph?

**Proposed Solution:**
See description in #29 

Aha! Link: https://imperial-college-ict.aha.io/requirements/RSE-140-9

**Comment by AdrianDAlessandro** [comment]
![Image](https://github.com/ImperialCollegeLondon/gridlington-vis/assets/40875798/f5be614e-9832-4075-a150-f0276df682ef)

**Comment by pclemow** [comment]
Possible script that allows for dealing with multiple dots in the same place:

import numpy as np
import math

SLD_out = open('./Files/Element_Test.svg', 'w')

header = "<?xml version=\"1.0\" encoding=\"utf-8\"?> \
\n \
\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\"> \
\n<svg version=\"1.1\" id=\"Layer_1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" \
x=\"0px\" y=\"0px\"\nwidth=\"400px\" height=\"400px\" viewBox=\"0 0 400 400\" " \
"enable-background=\"new 0 0 400 400\" xml:space=\"preserve\">\n"

agent_count = 1000
angle_mid = 180
angle_range = 30
rng = np.random.default_rng()
angles = rng.normal(loc=angle_mid, scale=angle_range, size=agent_count)
centre_x = 200
centre_y = 200
radius = 100  # base radius for the dots
radius_delta = 4  # how far to shift a dot if its home is filled
dot_size = 1.5  # how big is a dot
used_angles = np.ones(360)  # number of dots at each angle
outlines = []

#print(angles)

for agent in range(agent_count):
    dot_ang = int(round(angles[agent-1]))  # select our angle
    dot_r = radius + (radius_delta * used_angles[dot_ang-1])  # offset our dot so that its not on top of a previous one
    dot_xdiff = dot_r * math.cos(math.radians(dot_ang))  # x position of our dot (from centre)
    dot_ydiff = dot_r * math.sin(math.radians(dot_ang))  # y position of our dot (from centre)

    new_dot = "<circle fill=\"#6A0DAD\" stroke=\"#000000\" stroke-width=\"0\" cx=\"" + str(centre_x + dot_ydiff) \
              + "\" cy=\"" + str(centre_y + dot_xdiff) + "\" r=\"" + str(dot_size) + "\"/>\n"
    outlines.append(new_dot)
    used_angles[dot_ang-1] += 1  # mark down one more dot at this angle


node = "<circle fill=\"#FFFFFF\" stroke=\"#000000\" stroke-width=\"5\" cx=\"" + str(centre_x) + "\" cy=\"" \
       + str(centre_y) + "\" r=\"" + str(radius) + "\"/>\n"

new_node_num = "<text transform=\"matrix(1 0 0 1 " + str(centre_x) + " " + str(centre_y + 25) + \
               ")\" font-family=\"\'MyriadPro-Regular\'\" font-size=\"80\" text-anchor=\"middle\">" + \
               str(251) + "</text>\n"

outlines.append(node)
outlines.append(new_node_num)

SLD_out.write(header)

for outline in outlines:
    SLD_out.write(outline)

SLD_out.write('</svg>')

**Comment by AdrianDAlessandro** [comment]
![Image](https://github.com/ImperialCollegeLondon/gridlington-vis/assets/40875798/c99a8066-5bc2-4107-85c8-9ba859b12fc0)



![Image](https://github.com/ImperialCollegeLondon/gridlington-vis/assets/40875798/6a2e840e-2691-4ec0-8b8f-c121cb6db48f)
