### ISSUE TITLE
Deployment of vis system

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/gridlington-vis#38]
Update deployment of visualisation system on test server so that it uses Docker images from CI with automated updates.

**Comment by AdrianDAlessandro** [comment]
We will test the current VM setup to see if just one Vm is sufficient or if two are required.

**Comment by AdrianDAlessandro** [comment]
Need to confirm the WebRTC screen sharing function is working. Check it locally first.

Need to investigate the Shadow screens / lingering sections - currently when moving a section from one space to another, it moves to the new space, but also stays in the old one.
