### ISSUE TITLE
Document and type-hint callbacks in views

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/gridlington-vis#42]
**Problem:**
The QA in the callbacks in `app/pages/` has been ignored so far (because they are still not-finalised). Once they are complete, they need to be adequately documented and typed.

**Proposed Solution:**
This can be tackled iteratively with each of the new views as they are added. A review should be done at the end so that this issue can be closed.

Aha! Link: https://imperial-college-ict.aha.io/requirements/RSE-140-12

**Comment by tsmbland** [comment]
This all looks good now so I'll close the issue
