### ISSUE TITLE
Add a HTML App section to the OVE server

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/gridlington-vis#7]
Connect the Flask app endpoints to an [OVE HTML App](https://ove.readthedocs.io/en/stable/ove-apps/packages/ove-app-html/README.html) Using the [OVE Python API](https://ove.readthedocs.io/en/stable/ove-sdks/python/README.html).

Steps:
- [x] Manually set up one HTML App using the front end GUI. Requires Adding a _Section_ to a _Space_ and setting it up as an _HTML App_ using `http://localhost:8050/plot1` as the source.
- [x] Replicate that manual step with the Python API
- [x] Determine how to move/reassign views into different spaces. Does it require moving the section to a different space or just changing the source url for a given section?

**Comment by AdrianDAlessandro** [comment]
It appears that the Python Client Library is just an incomplete wrapper around the OVE Core API. So the best option is to probably persist with interacting directly with the Core API.

I suggest we approach this using the [Uplink library](https://uplink.readthedocs.io/en/stable/), which allows for an Object Oriented approach to interacting with APIs

**Comment by dandavies99** [comment]
> Determine how to move/reassign views into different spaces. Does it require moving the section to a different space or just changing the source url for a given section?

When changes from `api_test` branch are merged in, this final point should be clarified.
