### ISSUE TITLE
Deploy to final host machine

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/gridlington-vis#98]
**Problem:**
The vis system needs to be deployed to the new host machine once it is set up in the in the display room by @pclemow 

**Proposed Solution:**
Installed on the machine:
- Docker
- Python
- pip install pyyaml
- OpenVidu - needs to be installed and deployed, follow this process: https://docs.openvidu.io/en/stable/deployment/ce/on-premises/

Then you can deploy the vis system. Simplest way would be to clone this repo into a location like `/opt/gridlington/deployment/` and run `bash run.sh`. There might be a permissions issue with docker, then try `sudo bash run.sh`

Check logs with `docker compose logs` from inside this directory. Specifically check the dash app logs with `docker compose logs dash`

**Additional context:**
Some small changes will be required. Namely:
- The OPENVIDU_HOST environment variable will need to be updated to where the openvidu client is running. I think this should be done by changing the hard-coded location to using the `{ip}` variable and the appropriate port (note it needs to be https)
- I had to change the configuration for openvidu to run on port 4443 instead of 443 because those ports were being used by the datahub. It might be necessary again, or the datahub will need to use 4443 in the Caddy config instead (datahub using 4443 will required changing the ports in the environment feels defined by `configure.py`)

**Comment by dalonsoa** [comment]
The vis system has be deployed in the host machine with the following caveats:
- We did not deployed OpenVidu as it is used only to connect the NMX views, which seem to be causing too much trouble at the moment with all the WebRTC stuff, so they are being displayed directly without going through our application. 
- Running `run.sh` resulted in a production configuration being setup. For some reason, this did not work as `docker-compose` was complaining that a boolean value for [this entry](https://github.com/ImperialCollegeLondon/gridlington-vis/blob/07ea5acf423a4d248014835b3ed21244769e5ddb/configure.py#L89) was not valid. So we end up running the develop configuration.

@tsmbland , did I missed anything in relation to what we deployed for the vis system?

**Comment by dalonsoa** [comment]
Phil will review the current implementation over the next few weeks - screens content, layout, L&F, etc. - and will provide feedback on things that needs changing. This will be done, most likely, by him but with our support.

**Comment by tsmbland** [comment]
> @tsmbland , did I missed anything in relation to what we deployed for the vis system?

No I think that covers it. Thinking about it we would have had to run in develop mode anyway because if the `LIVE_MODEL` flag is set to `True` the vis system will try and connect to the DataHub rather than using the pre-set data (either that or we would have had to manually set `LIVE_MODEL` back to `False`). Presumably this is something we'd want easier control over, i.e. easy switching between the live model and preset data?
